// This is the code of the two conversion functions.
// The bind code generated by toLua++ is in ToLuaDemoBind.c

#include "core.h"

void polarToCartesian(float* r, float* alpha) {
  float rad = *r, alp = *alpha;
  float x = rad*cos(alp);
  float y = rad*sin(alp);
  *r = x; *alpha = y;
}

void cartesianToPolar(float* x, float* y) {
  float xx = *x, yy = *y;
  float r = sqrt(xx*xx+yy*yy);
  float alpha = atan2(xx,yy);
  *x = r; *y = alpha;
}
